# Brew & Bean Data Generation

## Project Objective
Generate a realistic coffee shop dataset for business intelligence analysis using Python.

The generated dataset will later be analysed in Excel and Power BI.

In [2]:
import pandas as pd
import numpy as np
from faker import Faker
import random
from datetime import datetime, timedelta

In [10]:
from pathlib import Path

# Project folders
DATA_DIR = Path("../data")
GENERATED_DIR = DATA_DIR / "generated"
PROCESSED_DIR = DATA_DIR / "processed"
EXTERNAL_DIR = DATA_DIR / "external"

In [3]:
fake = Faker()

RANDOM_SEED = 42

random.seed(RANDOM_SEED)
np.random.seed(RANDOM_SEED)
Faker.seed(RANDOM_SEED)

In [4]:
BRANCHES = [
    "Westlands",
    "Karen",
    "Kilimani",
    "CBD",
    "Runda"
]

PAYMENT_METHODS = [
    "Cash",
    "M-Pesa",
    "Debit Card",
    "Credit Card"
]

CUSTOMER_TYPES = [
    "Student",
    "Professional",
    "Tourist",
    "Remote Worker",
    "Regular"
]

In [5]:
print("Branches:", BRANCHES)
print("Payment Methods:", PAYMENT_METHODS)
print("Customer Types:", CUSTOMER_TYPES)

Branches: ['Westlands', 'Karen', 'Kilimani', 'CBD', 'Runda']
Payment Methods: ['Cash', 'M-Pesa', 'Debit Card', 'Credit Card']
Customer Types: ['Student', 'Professional', 'Tourist', 'Remote Worker', 'Regular']

In [15]:
branches_df = pd.DataFrame({
    "Branch_ID": [
        "BR001",
        "BR002",
        "BR003",
        "BR004",
        "BR005"
    ],

    "Branch_Name": [
        "Westlands",
        "Karen",
        "Kilimani",
        "CBD",
        "Runda"
    ],

    "City": [
        "Nairobi",
        "Nairobi",
        "Nairobi",
        "Nairobi",
        "Nairobi"
    ],

    "Area_Type": [
        "Commercial",
        "Residential",
        "Mixed",
        "Business District",
        "Residential"
    ],

    "Seating_Capacity": [
        70,
        55,
        65,
        90,
        45
    ],

    "Manager": [
        "Grace Mwangi",
        "Peter Otieno",
        "Diana Wanjiku",
        "Kevin Maina",
        "Faith Njeri"
    ],

    "Opening_Year": [
        2018,
        2020,
        2019,
        2016,
        2021
    ]
})

branches_df

,Branch_ID,Branch_Name,City,Area_Type,Seating_Capacity,Manager,Opening_Year
0,BR001,Westlands,Nairobi,Commercial,70,Grace Mwangi,2018
1,BR002,Karen,Nairobi,Residential,55,Peter Otieno,2020
2,BR003,Kilimani,Nairobi,Mixed,65,Diana Wanjiku,2019
3,BR004,CBD,Nairobi,Business District,90,Kevin Maina,2016
4,BR005,Runda,Nairobi,Residential,45,Faith Njeri,2021

In [16]:
branches_df.to_csv(
    GENERATED_DIR / "branches.csv",
    index=False
)

print("✅ branches.csv updated successfully!")

✅ branches.csv updated successfully!

branches_df.to_csv(GENERATED_DIR / "branches.csv", index=False) given we will now be using:

from pathlib import Path

# Project folders
DATA_DIR = Path("../data")
GENERATED_DIR = DATA_DIR / "generated"
PROCESSED_DIR = DATA_DIR / "processed"
EXTERNAL_DIR = DATA_DIR / "external"

Path helps us work with folders and files in a way that's cleaner and more reliable . If we reorganize the project, we only change the folder definition once instead of hunting through dozens of cells.

## Product Catalogue
Create the menu that Brew & Bean offers across all branches.

In [13]:
products_df = pd.DataFrame({
    "Product_ID": [
        "P001", "P002", "P003", "P004",
        "P005", "P006", "P007", "P008",
        "P009", "P010", "P011", "P012"
    ],

    "Product_Name": [
        "Espresso",
        "Americano",
        "Cappuccino",
        "Latte",
        "Vanilla Latte",
        "Mocha",
        "Hot Chocolate",
        "Chai Latte",
        "Blueberry Muffin",
        "Chocolate Croissant",
        "Chicken Sandwich",
        "Cheesecake"
    ],

    "Category": [
        "Coffee",
        "Coffee",
        "Coffee",
        "Coffee",
        "Coffee",
        "Coffee",
        "Non-Coffee",
        "Non-Coffee",
        "Pastry",
        "Pastry",
        "Food",
        "Dessert"
    ],

    "Price_KES": [
        220,
        250,
        350,
        380,
        420,
        400,
        340,
        330,
        280,
        300,
        550,
        450
    ],

    "Available_All_Year": [
        True, True, True, True,
        True, True, True, True,
        True, True, True, True
    ],

    "Calories": [
        5,
        8,
        180,
        210,
        260,
        240,
        300,
        250,
        420,
        480,
        650,
        510
    ]
})

products_df

,Product_ID,Product_Name,Category,Price_KES,Available_All_Year,Calories
0,P001,Espresso,Coffee,220,True,5
1,P002,Americano,Coffee,250,True,8
2,P003,Cappuccino,Coffee,350,True,180
3,P004,Latte,Coffee,380,True,210
4,P005,Vanilla Latte,Coffee,420,True,260
5,P006,Mocha,Coffee,400,True,240
6,P007,Hot Chocolate,Non-Coffee,340,True,300
7,P008,Chai Latte,Non-Coffee,330,True,250
8,P009,Blueberry Muffin,Pastry,280,True,420
9,P010,Chocolate Croissant,Pastry,300,True,480
10,P011,Chicken Sandwich,Food,550,True,650
11,P012,Cheesecake,Dessert,450,True,510

In [14]:
products_df.to_csv(
    GENERATED_DIR / "products.csv",
    index=False
)

print("✅ products.csv saved successfully!")

✅ products.csv saved successfully!

## Employee Data
Generate realistic employee records for each Brew & Bean branch.

In [17]:
job_roles = {
    "Branch Manager": 1,
    "Supervisor": 1,
    "Barista": 3,
    "Cashier": 2,
    "Kitchen Staff": 2
}

In [19]:
employees = []

employee_number = 1

for _, branch in branches_df.iterrows():

    for role, count in job_roles.items():

        for _ in range(count):

            employees.append({

                "Employee_ID": f"E{employee_number:04d}",

                "Employee_Name": fake.name(),

                "Branch_ID": branch["Branch_ID"],

                "Branch_Name": branch["Branch_Name"],

                "Job_Role": role,

                "Hire_Date": fake.date_between(
                    start_date="-6y",
                    end_date="today"
                ),

                "Monthly_Salary_KES": {
                    "Branch Manager": 95000,
                    "Supervisor": 70000,
                    "Barista": 38000,
                    "Cashier": 35000,
                    "Kitchen Staff": 34000
                }[role]

            })

            employee_number += 1

In [20]:
employees_df = pd.DataFrame(employees)

employees_df.head()

,Employee_ID,Employee_Name,Branch_ID,Branch_Name,Job_Role,Hire_Date,Monthly_Salary_KES
0,E0001,Mr. Nathaniel Khan,BR001,Westlands,Branch Manager,2025-07-21,95000
1,E0002,Richard Aguirre,BR001,Westlands,Supervisor,2022-04-09,70000
2,E0003,Matthew Gomez,BR001,Westlands,Barista,2024-02-24,38000
3,E0004,Nicholas Nunez,BR001,Westlands,Barista,2026-02-23,38000
4,E0005,James Morgan,BR001,Westlands,Barista,2021-07-31,38000

In [21]:
employees_df.to_csv(
    GENERATED_DIR / "employees.csv",
    index=False
)

print("✅ employees.csv saved successfully!")

✅ employees.csv saved successfully!

In [22]:
print(employees_df.info())
employees_df.describe(include="all")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45 entries, 0 to 44
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Employee_ID         45 non-null     object
 1   Employee_Name       45 non-null     object
 2   Branch_ID           45 non-null     object
 3   Branch_Name         45 non-null     object
 4   Job_Role            45 non-null     object
 5   Hire_Date           45 non-null     object
 6   Monthly_Salary_KES  45 non-null     int64
dtypes: int64(1), object(6)
memory usage: 2.6+ KB
None

,Employee_ID,Employee_Name,Branch_ID,Branch_Name,Job_Role,Hire_Date,Monthly_Salary_KES
count,45,45,45,45,45,45,45.000000
unique,45,45,5,5,5,44,NaN
top,E0001,Mr. Nathaniel Khan,BR001,Westlands,Barista,2021-01-30,NaN
freq,1,1,9,9,15,2,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,46333.333333
std,NaN,NaN,NaN,NaN,NaN,NaN,20499.445669
min,NaN,NaN,NaN,NaN,NaN,NaN,34000.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,35000.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,38000.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,38000.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,95000.000000

## Customer Data

Generate realistic Brew & Bean customers for loyalty and purchasing analysis.

In [23]:
NUM_CUSTOMERS = 500

random.choice() picks one item with equal chance.
random.choices() lets you assign weights.

In [24]:
customers = []

for i in range(1, NUM_CUSTOMERS + 1):

    customer_type = random.choices(
        population=[
            "Student",
            "Professional",
            "Remote Worker",
            "Tourist",
            "Regular"
        ],
        weights=[30, 35, 15, 5, 15],
        k=1
    )[0]

    customers.append({

        "Customer_ID": f"C{i:05d}",

        "Customer_Name": fake.name(),

        "Age": random.randint(18, 65),

        "Gender": random.choice([
            "Male",
            "Female"
        ]),

        "Customer_Type": customer_type,

        "Preferred_Branch": random.choice(
            BRANCHES
        ),

        "Loyalty_Member": random.choices(
            ["Yes", "No"],
            weights=[65, 35],
            k=1
        )[0],

        "Join_Date": fake.date_between(
            start_date="-5y",
            end_date="today"
        )

    })

In [25]:
customers_df = pd.DataFrame(customers)

customers_df.head()

,Customer_ID,Customer_Name,Age,Gender,Customer_Type,Preferred_Branch,Loyalty_Member,Join_Date
0,C00001,Courtney Velasquez,19,Female,Professional,Karen,Yes,2025-07-26
1,C00002,Robert Savage,61,Male,Remote Worker,Runda,Yes,2023-07-19
2,C00003,Corey Murphy,31,Male,Student,Runda,Yes,2022-03-29
3,C00004,Diana May,63,Female,Professional,Karen,Yes,2025-01-18
4,C00005,Sarah Rivera,18,Male,Student,CBD,Yes,2021-11-19

In [26]:
customers_df.to_csv(
    GENERATED_DIR / "customers.csv",
    index=False
)

print("✅ customers.csv saved successfully!")

✅ customers.csv saved successfully!

In [27]:
customers_df.info()
customers_df.describe(include="all")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Customer_ID       500 non-null    object
 1   Customer_Name     500 non-null    object
 2   Age               500 non-null    int64
 3   Gender            500 non-null    object
 4   Customer_Type     500 non-null    object
 5   Preferred_Branch  500 non-null    object
 6   Loyalty_Member    500 non-null    object
 7   Join_Date         500 non-null    object
dtypes: int64(1), object(7)
memory usage: 31.4+ KB

,Customer_ID,Customer_Name,Age,Gender,Customer_Type,Preferred_Branch,Loyalty_Member,Join_Date
count,500,500,500.000000,500,500,500,500,500
unique,500,498,NaN,2,5,5,2,444
top,C00500,Amanda Diaz,NaN,Male,Professional,Karen,Yes,2025-03-07
freq,1,2,NaN,251,164,112,318,3
mean,NaN,NaN,41.770000,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,13.614691,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,18.000000,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,30.000000,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,41.000000,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,53.250000,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,65.000000,NaN,NaN,NaN,NaN,NaN

## Sales Transactions

Generate realistic sales transactions across all Brew & Bean branches.

In [28]:
NUM_TRANSACTIONS = 50000

In [29]:
transactions = []

for i in range(1, NUM_TRANSACTIONS + 1):

    customer = customers_df.sample(1).iloc[0]
    product = products_df.sample(1).iloc[0]
    employee = employees_df.sample(1).iloc[0]

    quantity = random.randint(1, 3)

    transactions.append({

        "Transaction_ID": f"T{i:06d}",

        "Transaction_Date": fake.date_between(
            start_date="-2y",
            end_date="today"
        ),

        "Customer_ID": customer["Customer_ID"],

        "Branch_ID": employee["Branch_ID"],

        "Employee_ID": employee["Employee_ID"],

        "Product_ID": product["Product_ID"],

        "Quantity": quantity,

        "Unit_Price": product["Price_KES"],

        "Total_Amount": quantity * product["Price_KES"],

        "Payment_Method": random.choice(PAYMENT_METHODS)

    })

In [30]:
transactions_df = pd.DataFrame(transactions)

transactions_df.head()

,Transaction_ID,Transaction_Date,Customer_ID,Branch_ID,Employee_ID,Product_ID,Quantity,Unit_Price,Total_Amount,Payment_Method
0,T000001,2025-11-30,C00362,BR003,E0027,P006,2,400,800,Credit Card
1,T000002,2026-01-03,C00110,BR004,E0028,P004,3,380,1140,Credit Card
2,T000003,2026-08-06,C00269,BR003,E0024,P012,1,450,450,Cash
3,T000004,2024-10-31,C00409,BR002,E0013,P008,1,330,330,Debit Card
4,T000005,2024-11-18,C00442,BR003,E0027,P006,3,400,1200,Cash

In [31]:
transactions_df.to_csv(
    GENERATED_DIR / "transactions.csv",
    index=False
)

print("✅ transactions.csv saved successfully!")

✅ transactions.csv saved successfully!

In [32]:
transactions_df.info()
transactions_df.describe(include="all")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction_ID    50000 non-null  object
 1   Transaction_Date  50000 non-null  object
 2   Customer_ID       50000 non-null  object
 3   Branch_ID         50000 non-null  object
 4   Employee_ID       50000 non-null  object
 5   Product_ID        50000 non-null  object
 6   Quantity          50000 non-null  int64
 7   Unit_Price        50000 non-null  int64
 8   Total_Amount      50000 non-null  int64
 9   Payment_Method    50000 non-null  object
dtypes: int64(3), object(7)
memory usage: 3.8+ MB

,Transaction_ID,Transaction_Date,Customer_ID,Branch_ID,Employee_ID,Product_ID,Quantity,Unit_Price,Total_Amount,Payment_Method
count,50000,50000,50000,50000,50000,50000,50000.00000,50000.000000,50000.000000,50000
unique,50000,731,500,5,45,12,NaN,NaN,NaN,4
top,T049984,2025-11-13,C00169,BR004,E0026,P012,NaN,NaN,NaN,Credit Card
freq,1,92,130,10037,1198,4255,NaN,NaN,NaN,12670
mean,NaN,NaN,NaN,NaN,NaN,NaN,1.99336,356.029800,709.996000,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,0.81580,87.868595,347.166016,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,1.00000,220.000000,220.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,1.00000,300.000000,400.000000,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,2.00000,350.000000,660.000000,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,3.00000,420.000000,900.000000,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,3.00000,550.000000,1650.000000,NaN